name: flutter_dialogflow_v2
description: This package is useful to integrate dialogflow v2 in your Flutter project, it provides detectIntent request and response data with json mapping.
version: 0.3.1
author: Diego Dal Bosco <diegodalbo97@gmail.com>
repository: https://github.com/diegodalbosco/flutter_dialogflow
homepage: https://diegodalbosco.github.io/flutter_dialogflow/
issue_tracker: https://github.com/diegodalbosco/flutter_dialogflow/issues

dependencies:
  flutter:
    sdk: flutter
  http: any
  googleapis_auth: any
  meta: any

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: '>=2.1.0 <3.0.0'
